### ISSUE TITLE
[Adapting Code issue] 

### ISSUE THREAD

**Issue by seongmincho98** [IITP-Load-Balancing/SDV_Dynamic_Computation_Offloading_Controller#2]
What steps are required to adapt this program to my system?

**Comment by JUHO25** [comment]
1. In the **Target.cpp** code, ensure the following functions are utilized:
- readDefaultStatus
- updatePid
- signalHandler
2. Replace "Target" with "YourApp".
3. In the **default.txt** file, configure which functions should be executed at the initial startup based on user preferences.

**Comment by seongmincho98** [comment]
Thank you bro.&nbsp;

- Cho


-----Original Message-----From: "JUHO25" ***@***.***&gt;To: "IITP-Load-Balancing/SDV_Dynamic_Computation_Offloading_Controller" ***@***.***&gt;;Cc: "seongmincho98" ***@***.***&gt;; "Author" ***@***.***&gt;;Sent: 2024-11-19 (화) 16:53:44 (UTC+09:00)Subject: Re: [IITP-Load-Balancing/SDV_Dynamic_Computation_Offloading_Controller] [Adapting Code issue] (Issue #2)
